name: redbusclone
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:

  uses-material-design: true

  assets:
    - assets/logo.svg
    - assets/bus.svg
    - assets/account.svg
    - assets/calendar.svg
    - assets/help-mail.svg
    - assets/home.svg
    - assets/list-check.svg

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/AppIcons/Assets.xcassets/AppIcon.appiconset/180.png"
  min_sdk_android: 21

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
